sudo: false

language: node_js
node_js: node

cache:
  directories:
    - .elm

os:
  - linux

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - node --version
  - npm --version
  - npm install -g elm@0.19.0-no-deps elm-test@0.19.0-rev6

script:
  - elm-test
